apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: media-app
type: Opaque
data:
  mongo-user: bW9uZ29Vc2Vy        # base64("mongoUser")
  mongo-pass: bW9uZ29QYXNzMTIz    # base64("mongoPass123")
